# Generated by Django 2.0.4 on 2018-04-22 20:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0002_auto_20180422_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='roster',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
