# Generated by Django 2.0.4 on 2018-04-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0003_auto_20180422_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date won')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albo.User'),
        ),
        migrations.AlterField(
            model_name='team',
            name='roster',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trophy',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albo.Team'),
        ),
    ]
