# Generated by Django 2.0.4 on 2018-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0004_auto_20180423_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='jersey',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.TextField(blank=True),
        ),
    ]
