# Generated by Django 2.0.4 on 2018-04-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0005_auto_20180423_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='jersey',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.TextField(null=True),
        ),
    ]
