# Generated by Django 2.0.4 on 2018-04-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0006_auto_20180423_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('role1', models.CharField(max_length=3, null=True)),
                ('role2', models.CharField(max_length=3, null=True)),
                ('role3', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='roster',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='fantateam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albo.Team'),
        ),
    ]
