# Generated by Django 2.0.4 on 2018-04-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0007_auto_20180423_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('formato', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date won')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albo.User')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='date played')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albo.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albo.Matchday')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.FloatField()),
                ('fantavote', models.FloatField()),
                ('bonus', models.ManyToManyField(to='albo.Bonus')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albo.Matchday')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='team',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='teamirl',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fantateam',
        ),
        migrations.RemoveField(
            model_name='player',
            name='role1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='role2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='role3',
        ),
        migrations.AddField(
            model_name='team',
            name='yearroster',
            field=models.ManyToManyField(to='albo.Player'),
        ),
        migrations.DeleteModel(
            name='Trophy',
        ),
        migrations.AddField(
            model_name='performance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albo.Player'),
        ),
        migrations.AddField(
            model_name='matchroster',
            name='players',
            field=models.ManyToManyField(to='albo.Performance'),
        ),
        migrations.AddField(
            model_name='matchroster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albo.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='matchday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albo.Matchday'),
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(to='albo.MatchRoster'),
        ),
        migrations.AddField(
            model_name='player',
            name='roles',
            field=models.ManyToManyField(to='albo.Role'),
        ),
        migrations.AddField(
            model_name='team',
            name='competitions',
            field=models.ManyToManyField(to='albo.Competition'),
        ),
    ]
