# Generated by Django 2.0.4 on 2018-04-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0008_auto_20180424_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='formato',
        ),
    ]
