# Generated by Django 2.0.4 on 2018-04-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0010_performance_bench'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date won'),
        ),
    ]
