# Generated by Django 2.0.4 on 2018-04-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0012_auto_20180424_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='competitions',
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(to='albo.User'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='winner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='albo.Team'),
        ),
    ]
