# Generated by Django 2.0.4 on 2018-04-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0013_auto_20180424_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='yearroster',
            field=models.ManyToManyField(null=True, to='albo.Player'),
        ),
    ]
