# Generated by Django 2.0.4 on 2018-04-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0014_auto_20180424_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='participant', to='albo.User'),
        ),
        migrations.AlterField(
            model_name='team',
            name='yearroster',
            field=models.ManyToManyField(to='albo.Player'),
        ),
    ]
