# Generated by Django 2.0.4 on 2018-04-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0015_auto_20180424_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albo.Team'),
        ),
    ]
