# Generated by Django 2.0.4 on 2018-04-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0016_auto_20180424_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='matchday',
        ),
        migrations.RemoveField(
            model_name='matchroster',
            name='matchday',
        ),
        migrations.AddField(
            model_name='matchroster',
            name='home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='malus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='matchday',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Matchday',
        ),
    ]
