# Generated by Django 2.0.4 on 2018-04-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0018_auto_20180424_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='matchday',
            field=models.IntegerField(null=True),
        ),
    ]
