# Generated by Django 2.0.4 on 2018-04-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0019_game_matchday'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchroster',
            name='formation',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='matchroster',
            name='formation_applied',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
