# Generated by Django 2.0.4 on 2018-04-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0020_auto_20180424_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pseudoid',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
