# Generated by Django 2.0.4 on 2018-04-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0021_game_pseudoid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='pseudoid',
            new_name='pseudoid_game',
        ),
        migrations.AddField(
            model_name='matchroster',
            name='pseudoid_match',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
