# Generated by Django 2.0.4 on 2018-04-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0022_auto_20180424_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pseudoid_game',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchroster',
            name='pseudoid_match',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
