# Generated by Django 2.0.4 on 2018-04-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0023_auto_20180424_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='perf_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
