# Generated by Django 2.0.4 on 2018-04-24 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0024_performance_perf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchroster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_main', to='albo.Team'),
        ),
    ]
