# Generated by Django 2.0.4 on 2018-04-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0025_auto_20180424_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('matchday',)},
        ),
        migrations.AlterModelOptions(
            name='matchroster',
            options={'ordering': ('home',)},
        ),
        migrations.AddField(
            model_name='matchroster',
            name='fantapunti',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matchroster',
            name='goals',
            field=models.FloatField(null=True),
        ),
    ]
