# Generated by Django 2.0.4 on 2018-04-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0026_auto_20180425_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchroster',
            name='goals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
