# Generated by Django 2.0.4 on 2018-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0027_auto_20180425_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='toorder',
            field=models.IntegerField(null=True),
        ),
    ]
