# Generated by Django 2.0.4 on 2018-04-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0028_role_toorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('toorder',)},
        ),
    ]
