# Generated by Django 2.0.4 on 2018-04-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0029_auto_20180425_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('toorder',)},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.RemoveField(
            model_name='role',
            name='toorder',
        ),
        migrations.AddField(
            model_name='player',
            name='toorder',
            field=models.IntegerField(null=True),
        ),
    ]
