# Generated by Django 2.0.4 on 2018-04-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0030_auto_20180425_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='more_info',
            field=models.TextField(null=True),
        ),
    ]
