# Generated by Django 2.0.4 on 2018-04-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0031_game_more_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(null=True)),
                ('losses', models.IntegerField(null=True)),
                ('draws', models.IntegerField(null=True)),
                ('played', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('goal_for', models.IntegerField(null=True)),
                ('goal_against', models.IntegerField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albo.Team')),
            ],
            options={
                'ordering': ('points',),
            },
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.IntegerField(null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albo.Competition')),
                ('positions', models.ManyToManyField(to='albo.Position')),
            ],
        ),
        migrations.AlterModelOptions(
            name='matchroster',
            options={'ordering': ('-home',)},
        ),
    ]
