# Generated by Django 2.0.4 on 2018-04-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0032_auto_20180426_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='comp_format',
            field=models.CharField(default='season', max_length=200),
        ),
    ]
