# Generated by Django 2.0.4 on 2018-04-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0033_competition_comp_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albo.Competition'),
        ),
    ]
