# Generated by Django 2.0.4 on 2018-04-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0034_position_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='fantapunti',
            field=models.IntegerField(null=True),
        ),
    ]
