# Generated by Django 2.0.4 on 2018-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0035_position_fantapunti'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='matchday',
            field=models.IntegerField(null=True),
        ),
    ]
