# Generated by Django 2.0.4 on 2018-04-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0037_auto_20180427_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='goal_diff',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
