# Generated by Django 2.0.4 on 2018-04-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albo', '0038_position_goal_diff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('-points',)},
        ),
    ]
